"""
DATA_DOSSIER.md formatting utilities.

These utilities format the authoritative dataset reference document
produced by the DataDomainExpertAgent (DDEA).
"""

from typing import Any, Dict, List, Optional


def format_data_dossier(
    dataset_name: str,
    inventory: Optional[Dict[str, Any]] = None,
    schema: Optional[List[Dict[str, Any]]] = None,
    data_dictionary: Optional[List[Dict[str, Any]]] = None,
    column_profiles: Optional[List[Dict[str, Any]]] = None,
    relationships: Optional[Dict[str, Any]] = None,
    edge_cases: Optional[List[Dict[str, Any]]] = None,
    validation_rules: Optional[List[Dict[str, Any]]] = None,
    cleaning_plan: Optional[List[Dict[str, Any]]] = None,
    ml_readiness: Optional[Dict[str, Any]] = None,
    workflow_notes: Optional[str] = None,
    open_questions: Optional[List[str]] = None,
    change_log: Optional[List[Dict[str, Any]]] = None,
) -> str:
    """
    Format a complete DATA_DOSSIER.md from structured profiling components.

    Parameters
    ----------
    dataset_name : str
        Name/identifier of the dataset.
    inventory : dict, optional
        Dataset inventory: files, sizes, row counts, formats.
    schema : list of dict, optional
        Schema entries with keys: column, inferred_type, confidence,
        nullable, notes.
    data_dictionary : list of dict, optional
        Field-by-field definitions with keys: column, semantic_type,
        description, example_values, business_context.
    column_profiles : list of dict, optional
        Statistical profiles per column with keys: column, missing_pct,
        cardinality, min, max, mean, top_values, anomalies.
    relationships : dict, optional
        Join map and key relationships with keys: primary_keys,
        foreign_keys, join_recommendations.
    edge_cases : list of dict, optional
        Edge case findings with keys: column, issue_type, description,
        prevalence, handling_strategy, risk.
    validation_rules : list of dict, optional
        VAL-### rules with keys: rule_id, column, rule, severity,
        check_expression.
    cleaning_plan : list of dict, optional
        Ordered cleaning steps with keys: step, operation, columns,
        rationale, risk, reversible.
    ml_readiness : dict, optional
        ML readiness summary with keys: verdict, leakage_risks,
        feature_notes, encoding_recommendations.
    workflow_notes : str, optional
        Free-form workflow assurance notes.
    open_questions : list of str, optional
        Unresolved questions requiring investigation.
    change_log : list of dict, optional
        Change log entries with keys: date, version, change, author.

    Returns
    -------
    str
        Complete DATA_DOSSIER.md markdown content.
    """
    from datetime import datetime
    sections = []

    sections.append("# DATA_DOSSIER: %s" % dataset_name)
    sections.append("\n> **Generated by DataDomainExpertAgent (DDEA)**  \n> Last updated: %s\n" % datetime.now().strftime("%Y-%m-%d"))
    sections.append("---\n")

    # Table of Contents
    sections.append("## Table of Contents\n")
    toc_items = [
        "1. [Dataset Inventory](#1-dataset-inventory)",
        "2. [Schema & Types](#2-schema--types)",
        "3. [Data Dictionary](#3-data-dictionary)",
        "4. [Column Profiles](#4-column-profiles)",
        "5. [Relationships & Join Map](#5-relationships--join-map)",
        "6. [Edge Cases & Nuances](#6-edge-cases--nuances)",
        "7. [Validation Rules](#7-validation-rules)",
        "8. [Cleaning & Canonicalization Plan](#8-cleaning--canonicalization-plan)",
        "9. [ML Readiness Notes](#9-ml-readiness-notes)",
        "10. [Workflow Assurance Notes](#10-workflow-assurance-notes)",
        "11. [Open Questions & Uncertainties](#11-open-questions--uncertainties)",
        "12. [Change Log](#12-change-log)",
    ]
    sections.append("\n".join(toc_items))
    sections.append("\n---\n")

    # 1. Dataset Inventory
    sections.append("## 1. Dataset Inventory\n")
    if inventory:
        sections.append("| Property | Value |")
        sections.append("|----------|-------|")
        for k, v in inventory.items():
            sections.append("| %s | %s |" % (k.replace("_", " ").title(), str(v)))
    else:
        sections.append("_Inventory not yet profiled._")
    sections.append("")

    # 2. Schema & Types
    sections.append("## 2. Schema & Types\n")
    if schema:
        sections.append("| Column | Inferred Type | Confidence | Nullable | Notes |")
        sections.append("|--------|---------------|------------|----------|-------|")
        for row in schema:
            sections.append("| `%s` | %s | %s | %s | %s |" % (
                row.get("column", ""),
                row.get("inferred_type", ""),
                row.get("confidence", ""),
                row.get("nullable", ""),
                row.get("notes", ""),
            ))
    else:
        sections.append("_Schema not yet profiled._")
    sections.append("")

    # 3. Data Dictionary
    sections.append("## 3. Data Dictionary\n")
    if data_dictionary:
        for entry in data_dictionary:
            col = entry.get("column", "")
            sections.append("### `%s`\n" % col)
            sections.append("- **Semantic Type:** %s" % entry.get("semantic_type", "Unknown"))
            sections.append("- **Description:** %s" % entry.get("description", ""))
            sections.append("- **Business Context:** %s" % entry.get("business_context", ""))
            if entry.get("example_values"):
                sections.append("- **Example Values:** %s" % str(entry["example_values"])[:200])
            if entry.get("caveats"):
                sections.append("- **Caveats:** %s" % entry["caveats"])
            sections.append("")
    else:
        sections.append("_Data dictionary not yet compiled._")
    sections.append("")

    # 4. Column Profiles
    sections.append("## 4. Column Profiles\n")
    if column_profiles:
        sections.append("| Column | Missing % | Cardinality | Min | Max | Mean | Top Values | Anomalies |")
        sections.append("|--------|-----------|-------------|-----|-----|------|------------|-----------|")
        for prof in column_profiles:
            top_vals = str(prof.get("top_values", ""))[:60]
            anomalies = str(prof.get("anomalies", ""))[:60]
            sections.append("| `%s` | %s%% | %s | %s | %s | %s | %s | %s |" % (
                prof.get("column", ""),
                prof.get("missing_pct", ""),
                prof.get("cardinality", ""),
                prof.get("min", ""),
                prof.get("max", ""),
                prof.get("mean", ""),
                top_vals,
                anomalies,
            ))
    else:
        sections.append("_Column profiles not yet computed._")
    sections.append("")

    # 5. Relationships & Join Map
    sections.append("## 5. Relationships & Join Map\n")
    if relationships:
        if relationships.get("primary_keys"):
            sections.append("**Primary Keys:** %s" % ", ".join(
                "`%s`" % k for k in relationships["primary_keys"]
            ))
        if relationships.get("foreign_keys"):
            sections.append("\n**Foreign Keys:**")
            for fk in relationships["foreign_keys"]:
                sections.append("- `%s` references `%s`" % (
                    fk.get("column", ""), fk.get("references", "")
                ))
        if relationships.get("join_recommendations"):
            sections.append("\n**Join Recommendations:**")
            for rec in relationships["join_recommendations"]:
                sections.append("- %s" % rec)
    else:
        sections.append("_Relationships not yet analyzed._")
    sections.append("")

    # 6. Edge Cases & Nuances
    sections.append("## 6. Edge Cases & Nuances\n")
    if edge_cases:
        for i, ec in enumerate(edge_cases, 1):
            sections.append("### EC-%03d: %s — `%s`\n" % (i, ec.get("issue_type", ""), ec.get("column", "")))
            sections.append("- **Description:** %s" % ec.get("description", ""))
            sections.append("- **Prevalence:** %s" % ec.get("prevalence", "Unknown"))
            if ec.get("examples"):
                sections.append("- **Examples:** %s" % str(ec["examples"])[:200])
            sections.append("- **Handling Strategy:** %s" % ec.get("handling_strategy", ""))
            sections.append("- **Risk of Mishandling:** %s" % ec.get("risk", ""))
            if ec.get("do_not"):
                sections.append("- **Do NOT:** %s" % ec["do_not"])
            sections.append("")
    else:
        sections.append("_Edge cases not yet investigated._")
    sections.append("")

    # 7. Validation Rules
    sections.append("## 7. Validation Rules\n")
    if validation_rules:
        sections.append("| Rule ID | Column | Rule | Severity | Check Expression |")
        sections.append("|---------|--------|------|----------|-----------------|")
        for rule in validation_rules:
            sections.append("| %s | `%s` | %s | %s | `%s` |" % (
                rule.get("rule_id", ""),
                rule.get("column", ""),
                rule.get("rule", ""),
                rule.get("severity", ""),
                rule.get("check_expression", ""),
            ))
    else:
        sections.append("_Validation rules not yet defined._")
    sections.append("")

    # 8. Cleaning & Canonicalization Plan
    sections.append("## 8. Cleaning & Canonicalization Plan\n")
    if cleaning_plan:
        for i, step in enumerate(cleaning_plan, 1):
            sections.append("### Step %d: %s\n" % (i, step.get("operation", "")))
            sections.append("- **Columns:** %s" % str(step.get("columns", "All"))[:100])
            sections.append("- **Rationale:** %s" % step.get("rationale", ""))
            sections.append("- **Reversible:** %s" % step.get("reversible", "Yes"))
            sections.append("- **Risk:** %s" % step.get("risk", "Low"))
            sections.append("")
    else:
        sections.append("_Cleaning plan not yet defined._")
    sections.append("")

    # 9. ML Readiness
    sections.append("## 9. ML Readiness Notes\n")
    if ml_readiness:
        verdict = ml_readiness.get("verdict", "Unknown")
        sections.append("**Verdict:** %s\n" % verdict)
        if ml_readiness.get("leakage_risks"):
            sections.append("**Leakage Risks:**")
            for risk in ml_readiness["leakage_risks"]:
                sections.append("- %s" % risk)
        if ml_readiness.get("feature_notes"):
            sections.append("\n**Feature Notes:**")
            for note in ml_readiness["feature_notes"]:
                sections.append("- %s" % note)
        if ml_readiness.get("encoding_recommendations"):
            sections.append("\n**Encoding Recommendations:**")
            for rec in ml_readiness["encoding_recommendations"]:
                sections.append("- %s" % rec)
    else:
        sections.append("_ML readiness not yet assessed._")
    sections.append("")

    # 10. Workflow Assurance Notes
    sections.append("## 10. Workflow Assurance Notes\n")
    if workflow_notes:
        sections.append(workflow_notes)
    else:
        sections.append("_No workflow notes recorded._")
    sections.append("")

    # 11. Open Questions
    sections.append("## 11. Open Questions & Uncertainties\n")
    if open_questions:
        for q in open_questions:
            sections.append("- [ ] %s" % q)
    else:
        sections.append("_No open questions recorded._")
    sections.append("")

    # 12. Change Log
    sections.append("## 12. Change Log\n")
    if change_log:
        sections.append("| Date | Version | Change | Author |")
        sections.append("|------|---------|--------|--------|")
        for entry in change_log:
            sections.append("| %s | %s | %s | %s |" % (
                entry.get("date", ""),
                entry.get("version", ""),
                entry.get("change", ""),
                entry.get("author", "DDEA"),
            ))
    else:
        from datetime import datetime
        sections.append("| Date | Version | Change | Author |")
        sections.append("|------|---------|--------|--------|")
        sections.append("| %s | 1.0.0 | Initial dossier created | DDEA |" % datetime.now().strftime("%Y-%m-%d"))
    sections.append("")

    return "\n".join(sections)


def format_validation_rule_table(rules: List[Dict[str, Any]]) -> str:
    """
    Format a list of validation rules as a markdown table.

    Parameters
    ----------
    rules : list of dict
        Each dict: rule_id, column, rule, severity, check_expression.

    Returns
    -------
    str
        Markdown table.
    """
    if not rules:
        return "_No validation rules defined._"

    lines = [
        "| Rule ID | Column | Rule | Severity | Check Expression |",
        "|---------|--------|------|----------|-----------------|",
    ]
    for rule in rules:
        lines.append("| %s | `%s` | %s | %s | `%s` |" % (
            rule.get("rule_id", ""),
            rule.get("column", ""),
            rule.get("rule", ""),
            rule.get("severity", ""),
            rule.get("check_expression", ""),
        ))
    return "\n".join(lines)


def format_edge_case_summary(edge_cases: List[Dict[str, Any]]) -> str:
    """
    Format edge cases as a summary table.

    Parameters
    ----------
    edge_cases : list of dict
        Each dict: column, issue_type, prevalence, risk, handling_strategy.

    Returns
    -------
    str
        Markdown summary table.
    """
    if not edge_cases:
        return "_No edge cases detected._"

    lines = [
        "| # | Column | Issue Type | Prevalence | Risk | Handling |",
        "|---|--------|------------|------------|------|---------|",
    ]
    for i, ec in enumerate(edge_cases, 1):
        lines.append("| %d | `%s` | %s | %s | %s | %s |" % (
            i,
            ec.get("column", ""),
            ec.get("issue_type", ""),
            ec.get("prevalence", ""),
            ec.get("risk", ""),
            str(ec.get("handling_strategy", ""))[:60],
        ))
    return "\n".join(lines)


def format_a2a_response(
    intent: str,
    request_id: str,
    dataset_name: str,
    summary: str,
    details: Dict[str, Any],
    evidence: Optional[List[str]] = None,
    recommended_actions: Optional[List[str]] = None,
    risks_and_pitfalls: Optional[List[str]] = None,
    open_questions: Optional[List[str]] = None,
    confidence: str = "medium",
) -> str:
    """
    Format a structured A2A (Agent-to-Agent) response envelope.

    Parameters
    ----------
    intent : str
        The requested intent (e.g., 'dataset_overview', 'schema_and_types').
    request_id : str
        Unique request identifier.
    dataset_name : str
        Dataset name.
    summary : str
        Brief summary answer.
    details : dict
        Structured details per intent schema.
    evidence : list of str, optional
        Checks run, metrics computed, examples found.
    recommended_actions : list of str, optional
        Actionable next steps.
    risks_and_pitfalls : list of str, optional
        What could go wrong.
    open_questions : list of str, optional
        Unknowns + tests to resolve.
    confidence : str
        Confidence level: low, medium, high.

    Returns
    -------
    str
        Formatted A2A response as markdown.
    """
    lines = [
        "## A2A Response: %s" % intent.upper(),
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Intent | `%s` |" % intent,
        "| Request ID | `%s` |" % request_id,
        "| Dataset | `%s` |" % dataset_name,
        "| Confidence | **%s** |" % confidence.upper(),
        "",
        "### Summary",
        summary,
        "",
        "### Details",
    ]

    if isinstance(details, dict):
        for k, v in details.items():
            lines.append("**%s:**" % k.replace("_", " ").title())
            if isinstance(v, list):
                for item in v:
                    lines.append("- %s" % str(item))
            else:
                lines.append(str(v))
            lines.append("")
    else:
        lines.append(str(details))

    if evidence:
        lines.append("### Evidence")
        for e in evidence:
            lines.append("- %s" % e)
        lines.append("")

    if recommended_actions:
        lines.append("### Recommended Actions")
        for i, action in enumerate(recommended_actions, 1):
            lines.append("%d. %s" % (i, action))
        lines.append("")

    if risks_and_pitfalls:
        lines.append("### Risks & Pitfalls")
        for risk in risks_and_pitfalls:
            lines.append("- [RISK] %s" % risk)
        lines.append("")

    if open_questions:
        lines.append("### Open Questions")
        for q in open_questions:
            lines.append("- [ ] %s" % q)
        lines.append("")

    return "\n".join(lines)
